import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>JT&apos;s Personal Site</h1>

        <div style={{ width: "800px", margin: "0 auto", marginTop: "1rem" }}>
          <h2>About Me</h2>
          <p className={styles.description}>
            I grew up in Massachusetts in a family with 7 kids. After studying
            Computer Science at Boston University, I made my way to the west
            coast to explore the tech world. I now live in Santa Rosa with my
            lovely wife Mia, our young daughter Claire, and our troublemaker cat
            Wellington.
          </p>

          <p className={styles.description}>
            See below for some example projects I have worked on.
          </p>

          <div className={styles.grid}>
            <a
              href="https://github.com/QuotableWater7/btree"
              className={styles.card}
            >
              <h2>Rebalancing Binary Tree (JS)</h2>
              <p>
                As nodes are entered, tree makes a decision to rebalance the
                tree if the length to one child exceeds the length to another
                child by 2.
              </p>
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  width: "100%",
                  marginTop: "1rem",
                }}
              >
                <Image src="/tree.png" width="128" height="128" />
              </div>
            </a>

            <a href="/datadog.png" className={styles.card}>
              <h2>Application Monitoring</h2>
              <p>
                Added instrumentation to our webserver to clearly identify
                problem areas before the customer reports on them.
              </p>
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  width: "100%",
                  marginTop: "1rem",
                }}
              >
                <Image src="/datadog.png" width="128" height="128" />
              </div>
            </a>

            <a
              href="https://github.com/QuotableWater7/regex_simulator"
              className={styles.card}
            >
              <h2>Regular Expression Evaluator (JS)</h2>
              <p>
                Writes code to execute a regular expression by parsing a string
                into a series of tokens and evaluating regex rules.
              </p>
            </a>

            <a
              href="https://github.com/QuotableWater7/haskell-expression-eval"
              className={styles.card}
            >
              <h2>Mathematical Expression Evaluator (Haskell)</h2>
              <p>
                Takes a mathematical expression (as a string) and calculates the
                result.
              </p>
            </a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Written by JT Bowler, 2021</footer>
    </div>
  );
}
